import { Geist, Geist_Mono } from "next/font/google";

import { Header } from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";

import type { Metadata } from "next";

import "./globals.css";
import ProviderLayer from "@/app/ProviderLayer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Levity | Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <ProviderLayer>
          <main className="px-4 md:px-8 py-12">{children}</main>
        </ProviderLayer>
        <Footer />
      </body>
    </html>
  );
}
